celestiaorg/orchestrator-relayer

- go.mod
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/9
> chore: init go module

- evm/errors.go
- evm/ethereum_signature.go
- evm/evm_client.go
- evm/evm_transaction_opts.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/14
> Copy the EVM related code from Celestia-app

- types/attestation_confirm.go
- types/data_commitment_confirm.go
- types/errors.go
- types/valset_confirm.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/21
> Add attestation confirms types

- orchestrator/broadcaster.go
- orchestrator/orchestrator.go
- orchestrator/retrier.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/11
> Copy orchestrator implementation from Celestia-app

- p2p/querier.go
- rpc/app_querier.go
- rpc/tm_querier.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/41
> adds QGB querier interfaces 

- cmd/qgb/deploy/cmd.go
- cmd/qgb/relayer/cmd.go
- cmd/qgb/relayer/config.go
Mainly comments a function that we will eventually use when we stick the QGB implementation together.
> chore: changes for golang ci lint to pass

- testing/dht_network.go
- testing/errors.go
To avoid tests flakiness, we should wait for the DHTs to have their peers list populated before starting the tests.
> fix: wait for dhts to have peers before starting the tests

- p2p/dht_test.go
- p2p/keys.go
- p2p/keys_test.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/89
> feat: use evm address as key for confirms instead of orch addr

- evm/evm_client.go
- relayer/relayer.go
Contributes  to https://github.com/celestiaorg/orchestrator-relayer/issues/108
> chore: remove unnecessary EVM client interface

- orchestrator/orchestrator.go
- p2p/dht_test.go
- types/data_commitment_confirm.go
- types/valset_confirm.go
The `Msg` prefix was used as per the cosmos-sdk standard for naming messages. However, the confirms are no longer messages.
> chore: remove Msg prefix from confirms methods

- orchestrator/orchestrator.go
- p2p/errors.go
- p2p/querier.go
- p2p/querier_test.go
- relayer/relayer.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/90
Contributes to: https://github.com/celestiaorg/orchestrator-relayer/issues/108
> feat: implement p2p querier

- testing/evm_chain.go
> chore: stop the periodic commit when the test EVM chain is stopped

- orchestrator/orchestrator.go
- orchestrator/retrier.go
Contributes to: https://github.com/celestiaorg/orchestrator-relayer/issues/108
> chore: remove unnecessary Retrier interface

- go.mod
- go.sum
- rpc/suite_test.go
- testing/celestia_network.go
- testing/testnode.go
> chore: update celestia-app version

- cmd/qgb/helpers/parse.go
- cmd/qgb/helpers/parse_test.go
Will be used to parse bootstrappers from a comma separated list.
> feat: add ability to parse addr infos from strings

- p2p/dht.go
Reduces the routing table refresh period to a more realistic period. The value is taken from Celestia-node repo.
For IPFS, the value is 10 minutes:
> To keep the routing tables accurate and up to date, IPFS refreshes the routing table every 10 minutes. While this is likely a higher frequency than is strictly necessary, it's important to protect the network's health as IPFS learns more about the dynamics of the DHT network. A routing table refresh works as follows:
source: https://docs.ipfs.tech/concepts/dht/#routing-tables
I guess 1 minute is a good value given that our P2P network is still new and experimental.
We can reduce that to even 1 hour once we have enough validators running orchestrators.
> feat: reduce the routing table refresh period

- p2p/dht.go
- p2p/dht_test.go
- p2p/errors.go
- testing/dht_network.go
We need to support waiting for peers to be connected to the DHT before starting the orchestrator/relayer. This PR adds  a `WaitForPeers` function that does that and logs the current number of peers.
> feat: add qgb dht wait for peers

- orchestrator/orchestrator_test.go
- orchestrator/suite_test.go
- testing/qgb.go
- testing/testnode.go
Depends on https://github.com/celestiaorg/orchestrator-relayer/pull/133 and https://github.com/celestiaorg/orchestrator-relayer/pull/115
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/51
> test: add orchestrator tests

- relayer/relayer_test.go
Fixes main. Using 10sec wait for 500 blocks creates flakiness. Sometimes the chain reaches that height in time, sometimes it doesn't and the tests fail.
This PR increases the timeout and decrease the wait to 400 blocks so it always passes.
> test: increase relayer test wait for height timeout

- rpc/suite_test.go
- testing/celestia_network.go
Skip all the tests when running in `short` mode if they use Celestia testnode because of the race conditions and not to have to skip each one separatly.
> feat: skip all the tests in short mode if they use Celestia testnode

- cmd/qgb/orchestrator/cmd.go
- cmd/qgb/orchestrator/config.go
- cmd/qgb/relayer/cmd.go
- cmd/qgb/relayer/config.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/149 and https://github.com/celestiaorg/orchestrator-relayer/issues/156
> feat: add support for p2p listen address and identity

- p2p/querier.go
- p2p/querier_test.go
- relayer/relayer.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/180
> fix: update query 2/3 valset confirms to use the previous valset

- docs/deploy.md
- docs/keys.md
- docs/orchestrator.md
- docs/relayer.md
This PR standardizes the titles that are being used in https://github.com/celestiaorg/docs/pull/668 and resolves [lint errors](https://github.com/celestiaorg/docs/actions/runs/4737250543/jobs/8409824190?pr=668) that occurred when the markdown was imported from the `orchestrator-relayer` repo.
> docs: standardize titles for celestia docs & fix linting

- orchestrator/orchestrator.go
- rpc/errors.go
- rpc/tm_querier.go
- rpc/tm_querier_test.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/300
> feat: wait for block 1 before enqueuing missing nonces

- cmd/qgb/common/helpers.go
- helpers/retrier.go
> feat: implement simple exponential backoff for retries

- orchestrator/orchestrator.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/304
> fix: orchestrator sign up to last unbonding period

- cmd/qgb/orchestrator/config.go
- cmd/qgb/relayer/config.go
- docs/orchestrator.md
- docs/relayer.md
> chore: update the rpc flag name

- p2p/dht_test.go
This should fix a test that fails from time to time because the test isn't waiting for the second DHT routing table to populate:
https://github.com/celestiaorg/orchestrator-relayer/actions/runs/4773521264/jobs/8486641970
> test: wait also for second dht in test to pass before doing the checks

- cmd/qgb/base/config.go
- cmd/qgb/deploy/cmd.go
- cmd/qgb/deploy/config.go
- cmd/qgb/keys/common/common.go
- cmd/qgb/keys/evm/config.go
- cmd/qgb/keys/evm/evm.go
- cmd/qgb/keys/keys.go
- cmd/qgb/keys/p2p/config.go
- cmd/qgb/keys/p2p/p2p.go
- cmd/qgb/orchestrator/cmd.go
- cmd/qgb/orchestrator/config.go
- cmd/qgb/relayer/cmd.go
- cmd/qgb/relayer/config.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/270
> chore: show the default home directory in `--help`

- p2p/dht.go
Since we're relying on DHT values and not the providers. It would be better to disable them not to allow any party to send any related messages.
> feat: disable providers for DHT

- cmd/qgb/deploy/cmd.go
- cmd/qgb/deploy/config.go
- cmd/qgb/orchestrator/cmd.go
- cmd/qgb/orchestrator/config.go
- cmd/qgb/relayer/cmd.go
- cmd/qgb/relayer/config.go
1.  open [isssue](https://github.com/celestiaorg/orchestrator-relayer/issues/320). 
2. homeDir servic-name "relayer" was used as a string in cmd and config. Replaced with constant.
> chore: replace string with constant in homeDir

- docs/deploy.md
- docs/orchestrator.md
- docs/relayer.md
This PR links to the Celestia docs pages, instead of to the docs in the `orchestrator-relayer` repository.
The reasoning is that if we use relative links for docs i.e. `../qgb-binary.md`, it will break the links in the docs on the repository.
> fix: link to docs, instead of readme

- cmd/qgb/query/cmd.go
- cmd/qgb/query/config.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/332
The JSON file output is something like:
```json
[
{
"evmAddress": "0x91DEd26b5f38B065FC0204c7929Da1b2A21877Ad",
"signature": "d2862103cc5c27607b3fdd1c04bab52a921a837dc91748ddea9cf7b06fe0e10f568329e62eddcec25231216d4dcdd10941cab36db3ae7e838ef68606aca5ebef00",
"signed": true
},
{
"evmAddress": "0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488",
"signature": "1b0aca14ba92e2ce0adcb708a1be1587864cfa93342a820e7809e519536cc51331d7d7c75c1f5015355998d124351bbd46c9f763b0898eb98e802a3797ccc0bb01",
"signed": true
},
{
"evmAddress": "0x3EE99606625E740D8b29C8570d855Eb387F3c790",
"signature": "",
"signed": false
},
{
"evmAddress": "0x3d22f0C38251ebdBE92e14BBF1bd2067F1C3b7D7",
"signature": "",
"signed": false
}
]
```
> feat: support json output for query signers command

- cmd/qgb/query/cmd.go
The purpose of this command is to double-check that an orchestrator didn't post its signature, or is not running an orchestrator.
The reason for this is that sometimes, the command `qgb query signers` will take a long time to execute and fail to get all the provided values (there is an issue to investigate this). And some of the orchestrators' signatures are not returned.
Thus, this command can act as a double-checking tool so that Validators in BSR aren't missing points even if they're running the orchestrator correctly.
Note: this happened so far once, where I couldn't get the signature of a validator while he's running the orchestrator. However, I was able to get it using this command.
@mojtaba-esk this command doesn't support writing the output to file. However, if that's needed, let …
> feat: add query signature command

- orchestrator/orchestrator.go
- orchestrator/orchestrator_test.go
- orchestrator/suite_test.go
- testing/celestia_network.go
- testing/testnode.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/388
> feat: add support for orchestrator catchup on data commitments

- store/store.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/359
> feat: not lock the keys store when running orchestrator/relayer

- cmd/qgb/common/helpers.go
Closes: https://github.com/celestiaorg/orchestrator-relayer/issues/146
the output now is:
```
I[2023-06-20|16:59:54.071] loading EVM account                          address=0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488
I[2023-06-20|16:59:55.023] created host                                 
ID: 12D3KooWFb6jzki62cpRo87YWcwdJWwSADScEsNuCxiwa9xcQvQx
Listen addresses:
/ip4/192.168.1.11/tcp/30000
/ip4/127.0.0.1/tcp/30000
I[2023-06-20|17:00:05.024] waiting for routing table to populate        targetnumberofpeers=1 currentcount=0
```
> chore: pretty print listen addresses

- cmd/qgb/common/helpers.go
- cmd/qgb/orchestrator/cmd.go
- cmd/qgb/relayer/cmd.go
- relayer/relayer.go
- relayer/relayer_test.go
- store/init.go
- store/init_test.go
- store/store.go
- store/store_test.go
- testing/qgb.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/369
Refactors a bit the orchestrator/relayer initialization to be able to specify different store options.
> feat: make the relayer save the relayed signatures to store

- docs/deploy.md
- docs/keys.md
- docs/orchestrator.md
- docs/relayer.md
This PR matches the frontmatter (metadata) config on the Celestia docs site. This is being added to the source on the orchestrator-relayer repository as it will prevent the frontmatter from being removed when imported from this repository.
You can see in this [commit (ignore edit to package.json)](https://github.com/celestiaorg/docs/pull/1045/commits/6f5b05c04fe01015165244e80224fa5724f604de), a demonstration of what it would look like if the `importMarkdown.mjs` ran when the frontmatter does not exist on this source repository. This resolves #463
> documentation: match frontmatter on docs site .md files

- docs/orchestrator.md
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/473
> docs: add registering EVM address instructions

- docs/bootstrapper.md
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/344
> docs: add bootstrapper command docs

- Makefile
- docker/entrypoint.sh
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/483
> ci: fix makefile docker image build

- evm/evm_client.go
Currently, relaying attestations takes around 550000 gas, and deploying the contracts around 1250000 gas. So, we can reduce the default gas limit to a more realistic value.
> chore: reduce the default EVM gas limit

- .github/workflows/codeql.yml
> ci: add support for codeql

- orchestrator/orchestrator.go
- orchestrator/orchestrator_test.go
- orchestrator/suite_test.go
- relayer/suite_test.go
- rpc/suite_test.go
- testing/celestia_network.go
- testing/testnode.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/513
This makes the orchestrator signs by default, instead of needing to be part of a valset to sign. The only case it doesn't sign is when it finds a valset and it's not part of it.
> fix: make the orchestrator sign by default

- orchestrator/orchestrator.go
Just to avoid having an ugly log when starting the orchestrator since by definition, there is no prior valset to nonce 1:
```
core0-orch    | I[2023-10-12|00:07:52.579] processing nonce                             nonce=1
core0-orch    | D[2023-10-12|00:07:52.580] failed to query last valset before nonce (most likely pruned). signing anyway err="rpc error: code = Unknown desc = codespace qgb code 28: there is no valset before attestation nonce 1"
```
> fix: handle first nonce in orchestrator

- orchestrator/orchestrator.go
After thinking about this, there is no need to sign nonce 1 at all because if it is used, it will be the point of initialization of the QGB contract, thus, no need to sign it.
> chore: not sign nonce 1

- e2e/scripts/start_relayer.sh
- orchestrator/orchestrator.go
Increase the delay to start the relayer to reduce flakiness
> chore: increase relayer delay

- cmd/blobstream/relayer/cmd.go
- e2e/go.mod
- e2e/go.sum
- e2e/qgb_network.go
- evm/evm_client.go
- evm/evm_client_test.go
- go.mod
- go.sum
- relayer/relayer.go
> chore(deps): depend on blobstream contracts

- e2e/Dockerfile_e2e
- orchestrator/orchestrator.go
- rpc/app_querier.go
- rpc/app_querier_test.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/522
> feat: orchestrator signing up to earliest attestation nonce

- Makefile
- cmd/blobstream/root/cmd.go
- cmd/blobstream/version/build_info.go
- cmd/blobstream/version/version.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/517
Example output:
```shell
$ blobstream version
Semantic version: v1.0.0-rc4-2-gaa8af53-dev
Commit: aa8af539bae7ee504fd9d938cfe4fbac1a6f9779
Build Date: ven. 27 oct. 2023 22:50:52 CEST
System version: amd64/linux
Golang version: go1.21.1
```
> feat: add version command

- cmd/blobstream/deploy/cmd.go
- evm/evm_client.go
- orchestrator/broadcaster.go
- orchestrator/broadcaster_test.go
- orchestrator/orchestrator.go
- orchestrator/orchestrator_test.go
- p2p/dht.go
- p2p/dht_test.go
- p2p/errors.go
- p2p/keys.go
- p2p/querier.go
- p2p/validators.go
- p2p/validators_test.go
- relayer/errors.go
- relayer/relayer.go
- relayer/relayer_test.go
- types/latest_valset.go
- types/latest_valset_test.go
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/556
> feat: gossiping the latest valset in P2P layer in case they get pruned

- .github/workflows/ci-release.yml
- .goreleaser.yaml
Closes https://github.com/celestiaorg/orchestrator-relayer/issues/538
> ci: add support for goreleaser

- .github/workflows/test.yml
> ci: allow for test workflow call

- docs/bootstrapper.md
- docs/deploy.md
- docs/keys.md
- docs/orchestrator.md
- docs/relayer.md
This PR resolves build errors that occur on the documentation site as a result of no support for ssh syntax highlighting. The solution is to use sh.
Resolves https://github.com/celestiaorg/docs/issues/1171
> chore: resolve issues on docs runtime with use of ssh instead of sh 

- .github/workflows/lint.yml
- .github/workflows/test.yml
Removes duplicate CI calls since the setup of go-releaser
> ci: remove the duplicate CI runs

- docs/orchestrator.md
> docs: specify that validators should generate EVM addresses offchain
