celestiaorg/orchestrator-relayer

LICENSE

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/5

adds license to repo

---

.github/workflows/tag.yml

closes https://github.com/celestiaorg/orchestrator-relayer/issues/33

add tag github workflow

---

Makefile
scripts/test_cover.sh

closes  https://github.com/celestiaorg/orchestrator-relayer/issues/28

add Makefile

---

.github/workflows/test.yml

closes https://github.com/celestiaorg/orchestrator-relayer/issues/30

add test github workflow

---

cmd/qgb/deploy/cmd.go
cmd/qgb/deploy/config.go
cmd/qgb/deploy/errors.go
cmd/qgb/orchestrator/cmd.go
cmd/qgb/orchestrator/config.go
cmd/qgb/relayer/cmd.go
cmd/qgb/relayer/config.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/12

Add QGB commands backbone

---

.github/dependabot.yml

Updates the dependabot PRs reviewers. Do we need to add other people?

ci: update dependabot reviewers

---

.github/workflows/lint.yml
README.md

ci: add markdown lint and run lint on PRs

---

go.mod
types/data_commitment_confirm_test.go

Closes: https://github.com/celestiaorg/orchestrator-relayer/issues/52

test: add dcc sign bytes test

---

.github/workflows/lint.yml

ci: use go version 1.19 in lint

---

.github/workflows/lint.yml

ci: update golang ci lint version

---

.github/workflows/test.yml

ci: only run `split-test-files` if go files change

---

relayer/errors.go
relayer/relayer.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/19
The tests will be added when we have the testnode.

feat: add copied relayer implementation

---

relayer/relayer.go

Fixes the relayer after merging the new confirms types.

fix: fix relayer after merging to main

---

evm/evm_transaction_opts.go

chore: remove unused PrivateKeyPersonalSign implementation

---

go.mod
go.sum

chore: update celestia-app version to latest master

---

evm/evm_client_test.go
evm/suite_test.go
go.mod
go.sum
testing/evm_chain.go
testing/qgb.go
testing/testnode.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/106

test: add EVM client tests

---

go.mod
orchestrator/orchestrator.go
relayer/relayer.go
rpc/app_querier.go
rpc/app_querier_test.go
rpc/suite_test.go
types/errors.go

Contributes to: https://github.com/celestiaorg/orchestrator-relayer/issues/108
Closes: https://github.com/celestiaorg/orchestrator-relayer/issues/44

feat: implement app querier

---

cmd/qgb/deploy/cmd.go
cmd/qgb/deploy/config.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/49
Depends on: https://github.com/celestiaorg/orchestrator-relayer/pull/112

feat: implement the deploy command

---

cmd/qgb/main.go

feat: Enable QGB commands

---

testing/celestia_network.go

docs: specify how to get the EVM key used to create the CelestiaNetwork

---

testing/evm_chain.go

docs: document the test chain ID and put it in a const

---

orchestrator/retrier.go

Make the delay configurable in the retrier.

feat: add delay to retrier

---

testing/evm_chain.go

chore: reduce test EVM chain periodic commit delay

---

orchestrator/orchestrator.go

This is because the orchestrator will no longer be sending transactions to the Celestia network.

chore: remove unnecessary signer from orchestrator

---

orchestrator/orchestrator.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/108

chore: remove unnecessary orchestrator interface

---

orchestrator/retrier.go
orchestrator/retrier_test.go

Depends on: https://github.com/celestiaorg/orchestrator-relayer/pull/129

test: add retrier tests

---

p2p/querier.go
p2p/querier_test.go
relayer/relayer.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/119

feat: use ticker in queriers

---

p2p/dht_test.go

Addresses https://github.com/celestiaorg/orchestrator-relayer/pull/142#discussion_r1111482007

chore: use wait for peers in bootstrapper test

---

.github/CODEOWNERS
.github/dependabot.yml

chore: update code owners

---

go.mod
go.sum

chore: bump the app version

---

cmd/qgb/helpers/generate_cmd.go
cmd/qgb/main.go
cmd/qgb/orchestrator/config.go
cmd/qgb/relayer/config.go
go.mod

Creates a Generate command to be used to generate Ed25519 private keys in hex format to be  used in the orchestrator/relayer command.
It's only temporary until we support a better key management system.

feat: add support for generate command

---

cmd/qgb/deploy/cmd.go

fix: remove nil dereferencing in deploy logging

---

e2e/README.md

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/169

doc: add E2E README

---

e2e/Makefile

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/168

chore: add E2E makefile

---

rpc/app_querier.go
rpc/app_querier_test.go

feat: add query data commitment for height

---

go.mod
go.sum

chore: bump celestia-app version

---

.dockerignore

not to rebuild the E2E image if an unrelated change happened to the context as it takes  time to rebuild everything

feat: add dockerignore file

---

e2e/Makefile

This PR increases the e2e test timeout until we find a way to further speed it up.
Created issue to further speed up the E2E tests: https://github.com/celestiaorg/orchestrator-relayer/issues/208

chore: increase e2e test timeout

---

orchestrator/broadcaster_test.go
orchestrator/orchestrator.go
p2p/dht_test.go
p2p/querier_test.go
p2p/validators.go
p2p/validators_test.go
types/valset_confirm.go
types/valset_confirm_test.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/224

feat: implement valset confirm signature validation

---

e2e/qgb_network.go
orchestrator/broadcaster.go
orchestrator/broadcaster_test.go
orchestrator/orchestrator.go
orchestrator/orchestrator_test.go
p2p/dht_test.go
p2p/errors.go
p2p/keys.go
p2p/keys_test.go
p2p/querier.go
p2p/querier_test.go
p2p/validators.go
p2p/validators_test.go
relayer/relayer.go
relayer/relayer_test.go
types/data_commitment_confirm.go
types/data_commitment_confirm_test.go
types/valset_confirm.go
types/valset_confirm_test.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/225

feat: move the digest to the key instead of the value

---

cmd/qgb/relayer/cmd.go
relayer/relayer.go
testing/qgb.go

Adds retrier to Relayer so that if it fails, it retries a few times before exiting.
Also, closes: https://github.com/celestiaorg/orchestrator-relayer/issues/148
Also, contributes to: https://github.com/celestiaorg/orchestrator-relayer/issues/181

feat: add retrier to relayer

---

orchestrator/orchestrator.go
p2p/dht.go
p2p/querier.go
p2p/querier_test.go

Closes  https://github.com/celestiaorg/orchestrator-relayer/issues/152

feat: execute the queries once before the ticker

---

cmd/qgb/orchestrator/cmd.go
cmd/qgb/relayer/cmd.go

Reduces the wait period for p2p peers when starting the orchestrator and relayer.

chore: reduce wait period for p2p peers

---

orchestrator/orchestrator.go
relayer/relayer.go

docs: correct typos

---

.github/workflows/test.yml
helpers/retrier.go

chore: use ticker instead of sleep in retrier

---

relayer/relayer.go

chore: relayer waiting for nonce as debug message instead of info

---

.github/workflows/test.yml
p2p/dht.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/254

ci: fix don't cover failure

---

e2e/qgb_network.go

chore: better e2e logging

---

e2e/Dockerfile_e2e
e2e/celestia-app/config.toml
e2e/orchestrator_test.go
e2e/relayer_test.go
e2e/scripts/deploy_qgb_contract.sh
e2e/scripts/start_node_and_create_validator.sh
e2e/scripts/start_orchestrator_after_validator_created.sh

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/208

chore: tweaking e2e to execute faster

---

cmd/qgb/deploy/config.go
cmd/qgb/relayer/config.go
e2e/deployer_test.go
e2e/relayer_test.go
evm/evm_client.go
testing/celestia_network.go

Use a valid constant name that goes with how constants should be named in go.

chore: use valid `DefaultEVMGasLimit` constant name

---

e2e/orchestrator_test.go
e2e/relayer_test.go
e2e/test_commons.go

test: speed up e2e via forcing connection to DHT during tests

---

cmd/qgb/keys/common/common.go
cmd/qgb/keys/evm/evm.go
cmd/qgb/keys/keys.go
cmd/qgb/keys/p2p/config.go
cmd/qgb/keys/p2p/p2p.go
go.mod
store/store.go
store/store_test.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/64
A subsequent PR will make the orchestrator and relayer use this p2p store.

feat: add support for p2p keystore

---

cmd/qgb/base/config.go
cmd/qgb/deploy/cmd.go
cmd/qgb/deploy/config.go
cmd/qgb/keys/evm/config.go
cmd/qgb/keys/evm/evm.go
cmd/qgb/orchestrator/cmd.go
cmd/qgb/orchestrator/config.go
cmd/qgb/relayer/cmd.go
cmd/qgb/relayer/config.go
e2e/scripts/deploy_qgb_contract.sh
e2e/scripts/start_orchestrator_after_validator_created.sh
e2e/scripts/start_relayer.sh

chore:rename passphrase to EVM passphrase

---

cmd/qgb/keys/common/common.go
cmd/qgb/keys/p2p/p2p.go
cmd/qgb/keys/p2p/p2p_test.go
cmd/qgb/orchestrator/cmd.go
cmd/qgb/orchestrator/config.go
cmd/qgb/relayer/cmd.go
cmd/qgb/relayer/config.go
e2e/docker-compose.yml
e2e/scripts/start_orchestrator_after_validator_created.sh
e2e/scripts/start_relayer.sh

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/276

feat: integrate p2p keystore into orchestrator/relayer

---

e2e/Dockerfile_e2e

test: tweak e2e consensus timeout

---

cmd/qgb/orchestrator/config.go
e2e/scripts/start_orchestrator_after_validator_created.sh

chore: remove unnecessary orchestrator flag

---

e2e/scripts/deploy_qgb_contract.sh

chore: remove a duplicate flag from deploy script

---

cmd/qgb/common/helpers.go
cmd/qgb/deploy/cmd.go
cmd/qgb/keys/evm/evm.go
cmd/qgb/orchestrator/cmd.go
cmd/qgb/relayer/cmd.go

closes https://github.com/celestiaorg/orchestrator-relayer/issues/277
This is best we can do. If we want to refactor further, we will need to use some dependency injection framework

chore: refactor commands

---

docs/keys.md

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/268

docs: add keystore documentation

---

docs/deploy.md
docs/orchestrator.md
docs/relayer.md

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/2

docs: add orchestrator and relayer documentation

---

cmd/qgb/main.go
cmd/qgb/root/cmd.go

chore: move the root command to a separate package to be importable

---

p2p/dht.go

chore: revert to default RoutingTableRefreshPeriod

---

cmd/qgb/keys/evm/evm.go

chore: add new line when asking for password confirmation

---

cmd/qgb/deploy/config.go
cmd/qgb/orchestrator/config.go
cmd/qgb/relayer/config.go

Exports the commands flags to be used by testground

chore: export commands flags

---

README.md

This bumps the Go version to one that is compatible with BSR.

docs: bump go version in README.md

---

e2e/Dockerfile_e2e

Apparently, the current genesis is not compatible with the latest Celestia-app changes. We will update it along with the version when we bump the app version in the whole repo.

fix: use specific version for celestia-app in e2e

---

docs/orchestrator.md

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/308

docs: add validator requirement documentation

---

helpers/retrier.go
relayer/relayer.go

chore: better log

---

docs/orchestrator.md
docs/relayer.md

Style and linting for docs

---

cmd/qgb/keys/evm/evm.go

chore: better password confirmation log

---

.github/CODEOWNERS

chore: correct codeowners

---

cmd/qgb/query/cmd.go

1. added capacity in slice, as we are aware of capacity 
2. open [issue](https://github.com/celestiaorg/orchestrator-relayer/issues/322)

refactor : add capacity in stopfuncs slice

---

docs/orchestrator.md

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/325

docs: document systemd configuration for orchestrator

---

README.md
docs/orchestrator.md
docs/relayer.md

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/324

docs: document that the QGB p2p network is a separate one

---

docs/orchestrator.md

fix: linting

---

docs/orchestrator.md

From this job https://github.com/celestiaorg/docs/actions/runs/4928695173/jobs/8807373006?pr=741

resolve linting

---

docs/orchestrator.md

Docs were updated instead of this source page, and the docs are pulling in old source from this repo as a result.

fix: match docs

---

orchestrator/orchestrator.go

Temporary fix for: https://github.com/celestiaorg/orchestrator-relayer/issues/356
Will be merged to the BSR specific release branch and not to main.

fix: temporary fix for enqueuing missing nonces straight after an unbonding height

---

.github/workflows/lint.yml
.github/workflows/tag.yml
.github/workflows/test.yml
Dockerfile
Makefile
e2e/Dockerfile_e2e
go.mod

chore: bump go version to 1.20

---

cmd/qgb/generate/cmd.go
cmd/qgb/keys/p2p/p2p.go
go.mod

Fix CI for this https://github.com/celestiaorg/orchestrator-relayer/actions/runs/5086763797/jobs/9146718122

chore: replace deprecated NewTimeSeededRand

---

relayer/relayer.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/361

chore: increase relayer ticker

---

orchestrator/orchestrator.go
rpc/app_querier.go

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/356

fix: correctly choose the nonce to start signing from

---

cmd/qgb/base/config.go
cmd/qgb/deploy/cmd.go
cmd/qgb/deploy/config.go
cmd/qgb/orchestrator/cmd.go
cmd/qgb/orchestrator/config.go
cmd/qgb/query/cmd.go
cmd/qgb/query/config.go
cmd/qgb/relayer/cmd.go
cmd/qgb/relayer/config.go
docs/deploy.md
docs/orchestrator.md
docs/relayer.md
e2e/docker-compose.yml
e2e/scripts/deploy_qgb_contract.sh
e2e/scripts/start_orchestrator_after_validator_created.sh
e2e/scripts/start_relayer.sh

closes https://github.com/celestiaorg/orchestrator-relayer/issues/353

feat!: better parsing endpoints and flags refactor

---

docs/orchestrator.md

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/377

docs: remove unnecessary orchestrator indexing instructions

---

docs/orchestrator.md

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/367

docs: add P2P port instructions

---

README.md

docs: remove reference to QGB v1

---

.github/workflows/lables.yml

ci: add required labels workflow

---

go.mod
go.sum

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/432

chore(deps): bump core to v1.26.2

---

cmd/qgb/deploy/cmd.go
cmd/qgb/relayer/cmd.go
e2e/Dockerfile_e2e
e2e/docker-compose.yml
e2e/qgb_network.go
e2e/scripts/start_relayer.sh
evm/evm_client.go
go.mod
go.sum

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/460 and https://github.com/celestiaorg/orchestrator-relayer/issues/435

chore(deps): bump contracts version and update EVM deployments to support the upgradable proxy

---

Makefile

fix: makefile repo version

---

cmd/qgb/bootstrapper/cmd.go

chore: update the bootstrapper command description

---

.github/workflows/lint.yml
.github/workflows/tag.yml
.github/workflows/test.yml
Makefile
go.mod

chore(deps): bump go version to v1.21.1

---

docs/bootstrapper.md

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/479

chore(docs): confusing p2p key necessity in bootstrapper docs

---

docs/orchestrator.md

docs: mention the EVM key registeration when start orchestrator

---

e2e/Dockerfile_e2e

chore(deps): bump e2e dockerfile app version to rc17

---

.github/workflows/lint.yml

chore(deps): bump golang ci linter version

---

docs/bootstrapper.md
docs/deploy.md
docs/keys.md
docs/orchestrator.md
docs/relayer.md

docs: implement "no click here" on QGB docs

---

e2e/Dockerfile_e2e

chore(deps): bump E2E app version to 1.0.0

---

Dockerfile

Ref: https://github.com/celestiaorg/celestia-app/pull/2725

chore: fix multiplatform builds

---

.github/dependabot.yml

ci: add e2e go.mod to dependabot

---

benchmark/main.go

fix: update QGB to Blobstream in benchmark

---

.github/dependabot.yml

chore: rename the dependabot reviewer name
